// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLwrxmRIWg2S6Ju25dZNdkqxB_ozfzKo',
    appId: '1:864480272327:web:f5a6e921e6a964c6f383e2',
    messagingSenderId: '864480272327',
    projectId: 'ecommerce-d62e3',
    authDomain: 'ecommerce-d62e3.firebaseapp.com',
    storageBucket: 'ecommerce-d62e3.firebasestorage.app',
    measurementId: 'G-C6JJ2D1XZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrTEDy8W3iLcS_Phr-CrRU82laV0XiXbA',
    appId: '1:864480272327:android:4fb3e6d502bf0216f383e2',
    messagingSenderId: '864480272327',
    projectId: 'ecommerce-d62e3',
    storageBucket: 'ecommerce-d62e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyAdcQk1MnpV39UDMlkqeYIFgGwbzOaN4',
    appId: '1:864480272327:ios:4d83cb63e7d9ab97f383e2',
    messagingSenderId: '864480272327',
    projectId: 'ecommerce-d62e3',
    storageBucket: 'ecommerce-d62e3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyAdcQk1MnpV39UDMlkqeYIFgGwbzOaN4',
    appId: '1:864480272327:ios:4d83cb63e7d9ab97f383e2',
    messagingSenderId: '864480272327',
    projectId: 'ecommerce-d62e3',
    storageBucket: 'ecommerce-d62e3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJLwrxmRIWg2S6Ju25dZNdkqxB_ozfzKo',
    appId: '1:864480272327:web:88652636a654f479f383e2',
    messagingSenderId: '864480272327',
    projectId: 'ecommerce-d62e3',
    authDomain: 'ecommerce-d62e3.firebaseapp.com',
    storageBucket: 'ecommerce-d62e3.firebasestorage.app',
    measurementId: 'G-W967EGTJE1',
  );
}
